// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blueprint" | "/dashboard" | "/dashboard/architecture" | "/dashboard/compliance" | "/dashboard/data" | "/dashboard/dispatch" | "/dashboard/driver-app" | "/dashboard/drivers" | "/dashboard/fleet" | "/dashboard/heavy-driver-app" | "/dashboard/incident-report" | "/dashboard/invoice" | "/dashboard/jobs" | "/dashboard/live-map" | "/dashboard/passenger-app" | "/dashboard/price" | "/dashboard/products" | "/dashboard/reports" | "/dashboard/settings" | "/dashboard/shipper-portal" | "/dashboard/sms" | "/dashboard/support" | "/dashboard/tracking" | "/dashboard/weather" | "/fleet/tracking" | "/login" | "/payment"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/fleet"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/blueprint": {}
  "/dashboard": {}
  "/dashboard/architecture": {}
  "/dashboard/compliance": {}
  "/dashboard/data": {}
  "/dashboard/dispatch": {}
  "/dashboard/driver-app": {}
  "/dashboard/drivers": {}
  "/dashboard/fleet": {}
  "/dashboard/heavy-driver-app": {}
  "/dashboard/incident-report": {}
  "/dashboard/invoice": {}
  "/dashboard/jobs": {}
  "/dashboard/live-map": {}
  "/dashboard/passenger-app": {}
  "/dashboard/price": {}
  "/dashboard/products": {}
  "/dashboard/reports": {}
  "/dashboard/settings": {}
  "/dashboard/shipper-portal": {}
  "/dashboard/sms": {}
  "/dashboard/support": {}
  "/dashboard/tracking": {}
  "/dashboard/weather": {}
  "/fleet": {}
  "/fleet/tracking": {}
  "/login": {}
  "/payment": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/fleet": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
