// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/blueprint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blueprint">> = Specific
  const handler = {} as typeof import("../../src/app/blueprint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/architecture">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/compliance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/data">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/driver-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/driver-app">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/driver-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/drivers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/drivers">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/drivers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/heavy-driver-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/heavy-driver-app">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/heavy-driver-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/incident-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/incident-report">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/incident-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/live-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/live-map">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/live-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/passenger-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/passenger-app">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/passenger-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/price/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/price">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/price/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/shipper-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipper-portal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/shipper-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/sms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sms">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/sms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/weather/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/weather">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/weather/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fleet/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fleet/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/fleet/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment">> = Specific
  const handler = {} as typeof import("../../src/app/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fleet/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/fleet/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
