var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/products/route.js")
R.c("server/chunks/node_modules_next_0a8ce617._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/2a4f4_@grpc_grpc-js_da6826e2._.js")
R.c("server/chunks/node_modules_protobufjs_d7c441d2._.js")
R.c("server/chunks/node_modules_@firebase_firestore_dist_index_node_mjs_ae4421f5._.js")
R.c("server/chunks/node_modules_undici_32031a2a._.js")
R.c("server/chunks/node_modules_@firebase_auth_dist_node-esm_3ada34d4._.js")
R.c("server/chunks/node_modules_@firebase_storage_dist_node-esm_index_node_esm_b8fb09e7.js")
R.c("server/chunks/node_modules_f6e9d5f1._.js")
R.c("server/chunks/[root-of-the-server]__4b633746._.js")
R.m("[project]/.next-internal/server/app/api/products/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/products/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/products/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
